{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "7be38f9f-8a61-43de-af20-3132c70f8f0d",
   "metadata": {},
   "source": [
    "# Handling Different Exceptions in Python"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "93280859-f80b-4c31-b8fd-8e18b56805af",
   "metadata": {},
   "source": [
    "# ## SyntaxError\n",
    "# This error is generated by the interpreter if there is a syntax error in the code.\n",
    "# Uncommenting the following code will raise a SyntaxError.\n",
    "# ```python\n",
    "# eval('x === x')\n",
    "# ```\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c2672e59-b843-4775-bf32-3d4555f1d3de",
   "metadata": {},
   "source": [
    "# ## IndentationError\n",
    "# This error occurs when there is incorrect indentation in the code."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5662c067-567e-4df4-9918-0e8d792036f0",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "try:\n",
    "    def faulty_function():\n",
    "        print(\"Hello\")\n",
    "     # Incorrect indentation here\n",
    "      print(\"World\")\n",
    "except IndentationError as e:\n",
    "    print(f\"IndentationError: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5371abbb-0e45-4b01-be20-aba13f2f847a",
   "metadata": {},
   "source": [
    "# ## TypeError\n",
    "# This error occurs when an operation is applied to an object of inappropriate type."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bedf301e-cc5f-48ad-960a-09332eb43f43",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    result = 'string' + 5\n",
    "except TypeError as e:\n",
    "    print(f\"TypeError: {e}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "91e2e431-ee69-4509-9c09-9696619f90bc",
   "metadata": {},
   "source": [
    "# ## ValueError\n",
    "# This error occurs when a function receives an argument of the correct type but inappropriate value.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "de42be9e-8721-4b13-997e-ec474597eaaa",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    number = int('not_a_number')\n",
    "except ValueError as e:\n",
    "    print(f\"ValueError: {e}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "542970da-04cc-4fb2-9670-388fbb98d4b2",
   "metadata": {},
   "source": [
    "# ## IndexError\n",
    "# This error occurs when a sequence subscript is out of range."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "294e0316-af29-4e74-a2e7-0e08bc1cc9f7",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    my_list = [1, 2, 3]\n",
    "    item = my_list[10]\n",
    "except IndexError as e:\n",
    "    print(f\"IndexError: {e}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "674db47d-3a37-438e-9564-5137aba0476d",
   "metadata": {},
   "source": [
    "# ## KeyError\n",
    "# This error occurs when a dictionary key is not found."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "80001eda-4a77-41ca-aecf-7d1badf3f4fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    my_dict = {'a': 1}\n",
    "    value = my_dict['b']\n",
    "except KeyError as e:\n",
    "    print(f\"KeyError: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fa902991-1013-487d-926e-48ba4774aaab",
   "metadata": {},
   "source": [
    "# ## FileNotFoundError\n",
    "# This error occurs when trying to open a file that does not exist."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0b9dfadf-b3ba-4935-8261-579510255b49",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    with open('non_existent_file.txt', 'r') as file:\n",
    "        content = file.read()\n",
    "except FileNotFoundError as e:\n",
    "    print(f\"FileNotFoundError: {e}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7be9d819-44a2-41be-a273-7470bca612d8",
   "metadata": {},
   "source": [
    "# ## Handling Multiple Exceptions\n",
    "# You can handle multiple exceptions in a single `try` block.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "09cee67f-b010-4651-ba2c-226f0a0cc902",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    # Uncomment the following line to generate a ValueError\n",
    "    number = int('not_a_number')\n",
    "    \n",
    "    # Uncomment the following line to generate a ZeroDivisionError\n",
    "    result = 10 / 0\n",
    "    \n",
    "    # Uncomment the following line to generate an IndexError\n",
    "    my_list = [1, 2, 3]\n",
    "    item = my_list[10]\n",
    "    \n",
    "    # Uncomment the following line to generate a FileNotFoundError\n",
    "    with open('non_existent_file.txt', 'r') as file:\n",
    "        content = file.read()\n",
    "\n",
    "    # Uncomment the following line to generate an ImportError\n",
    "    import non_existent_module\n",
    "    \n",
    "    pass  # Replace this with code that might raise an exception\n",
    "except (ValueError, ZeroDivisionError, IndexError, FileNotFoundError, ImportError) as e:\n",
    "    print(f\"Handled exception: {e}\")\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
